version: '3.8'

services:
  dateme-backend:
    container_name: dateme-backend
    build: .
    image: dateme-backend

    ports:
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    command: /bin/bash -c "/app/pre-start.sh && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  db:
    container_name: postgresql_db
    image: postgres:16

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata


volumes:
  postgres_data:
