"""Initial migration

Revision ID: 597e0a93c5c7
Revises: d654dc4996a7
Create Date: 2024-02-14 12:09:19.996240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597e0a93c5c7'
down_revision = 'd654dc4996a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
