"""added location

Revision ID: 719737cbd988
Revises: 7bc5fa2dab8f
Create Date: 2024-04-16 12:34:56.160085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719737cbd988'
down_revision = '7bc5fa2dab8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
