"""added location

Revision ID: abde43cae0db
Revises: 719737cbd988
Create Date: 2024-04-16 12:39:42.552684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abde43cae0db'
down_revision = '719737cbd988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'userlocation', ['current_location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'current_location')
    # ### end Alembic commands ###
